logging:
  config: classpath:logback-spring-local.xml
spring:
  rabbitmq:
      host: 192.168.0.90
      port: 5672
      username: sziov
      password: sziov
  security:
    user:
      name: sziov
      password: sziov
#忽略权限拦截，外部系统，例如springboot admin 和mq刷新配置都需要权限
management:
  endpoints:
    web:
      exposure:
        #开放所有页面节点  默认只开启了health、info两个节点，注意yml的*要使用双引号
        include: "*"
  endpoint:
    health:
      #显示健康具体信息  默认不会显示详细信息
      show-details: ALWAYS